Add jest
chuotchet/redux pull request #4
Opened 2018-10-12 10:34 UTC by chuotchet

2018-10-12 10:55 UTC, leo-le-07 requested changes
Some feedbacks add, please notice test structure and indentation 😄

2018-10-12 10:55 UTC, leo-le-07 commented on examples/todos/src/containers/AddTodo.test.js
> +    it('should match snapshot', () => {
For submitting action, maybe we missing test case here.
- What if `value` is empty when we click on submit button? We should not do anything: dispatch value or set update state, right?

2018-10-12 10:55 UTC, leo-le-07 commented on examples/todos/src/containers/AddTodo.test.js
> +describe('Test AddTodo',  () => {
The structure for this testing should be:
```javascript
describe('AddTodo', () => {
  describe('handleSubmit', () => {
    it('should not do anything when value is empty', () => {
      ...
    });
    it('should prevent event default action', () => {
      ...
    });
    ...
  });
  describe('handleChange', () => {
    it('should state value correctly', () => {
      ...
    });
  });
})
```

2018-10-12 10:55 UTC, leo-le-07 commented on examples/todos/src/actions/index.test.js
> +  it('addTodo should create ADD_TODO action', () => {
Normally we separate the method we want to test to one more nested describe, such as:
```javascript
describe('addTodo', () => {
  it('should create ....', () => {
  });
});
```

2018-10-12 10:55 UTC, leo-le-07 commented on examples/todos/src/components/Link.test.js
> +const setup = (setupProps = {}) => {
Indentation warning, 2 spaces is enough instead of 4 spaces per 1 tab.

2018-10-12 10:55 UTC, leo-le-07 commented on examples/todos/src/components/TodoList.test.js
> +    const defaultProps = {
Indentation warning, 2 spaces is enough instead of 4 spaces per 1 tab.

2018-10-12 10:55 UTC, leo-le-07 commented on examples/todos/src/containers/FilterLink.test.js
> +describe('Test FilterLink', () => {
No need `Test` in `describe`, we know that we're in testing context, right? 😄

2018-10-15 02:07 UTC, leo-le-07 commented on examples/todos/src/containers/AddTodo.test.js
> +    })
Maybe we're missing a case that `when value is present`, right?

2018-10-15 02:07 UTC, leo-le-07 commented on examples/todos/src/containers/AddTodo.test.js
> +    })
Oh, one more thing can make us misunderstand here, `The structure for this testing should be` I commented before, it means that how the test structure should be with `describe` and `it`. That's a suggestion to write a better understandable test.
Maybe that's why you remove the case when value is present 😄

2018-10-15 02:19 UTC, chuotchet commented on examples/todos/src/containers/AddTodo.test.js
> +    })
the case when value is present is under `should state value correctly`, isn't is? 😕

2018-10-15 02:39 UTC, leo-le-07 commented on examples/todos/src/containers/AddTodo.test.js
> +    })
It's different. So after you submitting form, the state's value should be reset to empty, right? We should have a test to check this case. Does it make sense?

2018-10-15 03:13 UTC, leo-le-07 approved these changes

2018-10-15 03:18 UTC, merged